from sqlalchemy import Column, Integer, String, DateTime, Text, ForeignKey, Boolean
from datetime import datetime, timezone
from .database import Base

class User(Base):
    __tablename__ = "users"

    id              = Column(Integer, primary_key=True, index=True, autoincrement=True)
    username        = Column(String(100), unique=True, index=True, nullable=False)
    email           = Column(String(255), unique=True, index=True, nullable=False)
    hashed_password = Column(String(255), nullable=False)
    role            = Column(String(20), default="citizen")   # "citizen" | "lawyer"
    created_at      = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

    # Lawyer verification gate —————————————————————————————————————————————
    # When a user registers requesting the 'lawyer' role:
    #   - role is set to 'citizen' (no immediate privilege escalation)
    #   - lawyer_verification_pending is set to True
    #   - bar_council_id stores the self-reported Bar Council Enrollment ID
    # An admin must manually verify and flip role -> 'lawyer' and
    # lawyer_verification_pending -> False via the admin endpoint.
    # TODO: Build an admin-approval endpoint (see auth_routes.py)
    lawyer_verification_pending = Column(Boolean, nullable=False, default=False)
    bar_council_id              = Column(String(100), nullable=True, default=None)

class CaseMetadata(Base):
    """Stores metadata about downloaded SC judgments"""
    __tablename__ = "case_metadata"

    id         = Column(Integer, primary_key=True, index=True, autoincrement=True)
    case_name  = Column(Text, nullable=True)
    year       = Column(Integer, nullable=True)
    case_type  = Column(String(100), nullable=True)
    pdf_path   = Column(Text, nullable=True)
    link       = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

class Conversation(Base):
    """Stores citizen chatbot conversations"""
    __tablename__ = "conversations"

    id        = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id   = Column(Integer, ForeignKey("users.id"), nullable=False)
    question  = Column(Text, nullable=False)
    answer    = Column(Text, nullable=False)
    timestamp = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

class Draft(Base):
    """Stores AI-generated legal documents"""
    __tablename__ = "drafts"

    id         = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id    = Column(Integer, ForeignKey("users.id"), nullable=False)
    doc_type   = Column(String(100), nullable=False)
    title      = Column(String(255), nullable=False)
    content    = Column(Text, nullable=False)
    form_data  = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc))

class SimilaritySearch(Base):
    """Stores lawyer similarity search queries and results"""
    __tablename__ = "similarity_searches"

    id            = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id       = Column(Integer, ForeignKey("users.id"), nullable=False)
    query         = Column(Text, nullable=False)
    results_json  = Column(Text, nullable=True)
    strategy_text = Column(Text, nullable=True)   # nullable — old rows won't have it
    timestamp     = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))

class LawyerDocument(Base):
    """Stores documents generated by lawyers (Bail, Legal Notice, etc.)"""
    __tablename__ = "lawyer_documents"

    id            = Column(Integer, primary_key=True, index=True, autoincrement=True)
    user_id       = Column(Integer, ForeignKey("users.id"), nullable=False)
    document_type = Column(String(100), nullable=False) # "bail", "legal_notice", "written_arguments"
    case_title    = Column(String(255), nullable=False)
    content       = Column(Text, nullable=False)
    form_data     = Column(Text, nullable=True) # JSON store for form inputs
    created_at    = Column(DateTime(timezone=True), default=lambda: datetime.now(timezone.utc))
