import json
import io
import os
from pathlib import Path
from fastapi import APIRouter, Depends, HTTPException, Response
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from ...db.database import get_db
from ...db.models import User, LawyerDocument
from ...core.auth import require_lawyer
from ...services.vector_service import vector_service
from fpdf import FPDF
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import matplotlib

router = APIRouter(tags=["Lawyer - Litigation Documents"])

@router.post("/generate-bail")
def generate_bail(body: dict, current_user: User = Depends(require_lawyer), db: Session = Depends(get_db)):
    details = body.get("details")
    case_title = body.get("case_title", "Bail Application")
    if not details:
        raise HTTPException(status_code=400, detail="Missing details")
    
    result = vector_service.generate_lawyer_litigation_document("bail", {"details": details})
    content = result["content"]
    verification = result["verification"]
    
    doc = LawyerDocument(
        user_id=current_user.id,
        document_type="bail",
        case_title=case_title,
        content=content,
        form_data=json.dumps(body)
    )
    db.add(doc)
    db.commit()
    db.refresh(doc)
    
    return {
        "id": doc.id,
        "case_title": doc.case_title,
        "document_type": doc.document_type,
        "content": doc.content,
        "created_at": doc.created_at,
        "verification": verification,
    }

@router.post("/generate-legal-notice")
def generate_legal_notice(body: dict, current_user: User = Depends(require_lawyer), db: Session = Depends(get_db)):
    details = body.get("details")
    case_title = body.get("case_title", "Legal Notice")
    if not details:
        raise HTTPException(status_code=400, detail="Missing details")
    
    result = vector_service.generate_lawyer_litigation_document("legal_notice", {"details": details})
    content = result["content"]
    verification = result["verification"]
    
    doc = LawyerDocument(
        user_id=current_user.id,
        document_type="legal_notice",
        case_title=case_title,
        content=content,
        form_data=json.dumps(body)
    )
    db.add(doc)
    db.commit()
    db.refresh(doc)
    
    return {
        "id": doc.id,
        "case_title": doc.case_title,
        "document_type": doc.document_type,
        "content": doc.content,
        "created_at": doc.created_at,
        "verification": verification,
    }

@router.post("/generate-written-arguments")
def generate_written_arguments(body: dict, current_user: User = Depends(require_lawyer), db: Session = Depends(get_db)):
    details = body.get("details")
    case_title = body.get("case_title", "Written Arguments")
    if not details:
        raise HTTPException(status_code=400, detail="Missing details")
    
    result = vector_service.generate_lawyer_litigation_document("written_arguments", {"details": details})
    content = result["content"]
    verification = result["verification"]
    
    doc = LawyerDocument(
        user_id=current_user.id,
        document_type="written_arguments",
        case_title=case_title,
        content=content,
        form_data=json.dumps(body)
    )
    db.add(doc)
    db.commit()
    db.refresh(doc)
    
    return {
        "id": doc.id,
        "case_title": doc.case_title,
        "document_type": doc.document_type,
        "content": doc.content,
        "created_at": doc.created_at,
        "verification": verification,
    }

@router.get("/")
def list_documents(current_user: User = Depends(require_lawyer), db: Session = Depends(get_db)):
    return db.query(LawyerDocument).filter(LawyerDocument.user_id == current_user.id).order_by(LawyerDocument.created_at.desc()).all()

@router.delete("/{doc_id}", status_code=200)
def delete_document(doc_id: int, current_user: User = Depends(require_lawyer), db: Session = Depends(get_db)):
    doc = db.query(LawyerDocument).filter(
        LawyerDocument.id == doc_id,
        LawyerDocument.user_id == current_user.id
    ).first()
    if not doc:
        raise HTTPException(status_code=404, detail="Not found")
    db.delete(doc)
    db.commit()
    return {"success": True, "deleted_id": doc_id}


@router.post("/export-docx")
def export_docx(body: dict, current_user: User = Depends(require_lawyer)):
    """Export a litigation document as an editable DOCX file.
    Fully Unicode-safe — handles ₹, em-dashes, smart quotes, and all
    characters generated by the LLM without error.
    """
    content = body.get("content")
    title   = body.get("title", "Document")
    if not content:
        raise HTTPException(status_code=400, detail="No content to export")

    doc = Document()

    # ── Margins: 1 inch all sides (standard court document) ──────────
    for section in doc.sections:
        section.top_margin    = Inches(1)
        section.bottom_margin = Inches(1)
        section.left_margin   = Inches(1.25)
        section.right_margin  = Inches(1.25)

    # ── Title (bold, centred, 14pt Times New Roman) ───────────────────
    heading = doc.add_paragraph()
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = heading.add_run(title)
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(14)
    doc.add_paragraph()  # blank line after title

    # ── Body: one paragraph per line, 12pt Times New Roman ───────────
    for line in content.split("\n"):
        para = doc.add_paragraph(line)
        para.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY
        for run in para.runs:
            run.font.name = "Times New Roman"
            run.font.size = Pt(12)

    file_stream = io.BytesIO()
    doc.save(file_stream)
    file_stream.seek(0)

    safe_title = title.encode("ascii", "ignore").decode("ascii").replace(" ", "_").replace("/", "-").replace("\\", "-")
    return StreamingResponse(
        file_stream,
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f'attachment; filename="{safe_title}.docx"'}
    )


@router.post("/export-pdf")
def export_pdf(body: dict, current_user: User = Depends(require_lawyer)):
    """Export a litigation document as PDF.
    Uses DejaVu Sans (bundled with matplotlib) instead of fpdf2's core
    helvetica font, which is Latin-1 only and crashes on ₹, em-dashes,
    smart quotes, and other Unicode characters in LLM-generated content.
    """
    content = body.get("content")
    title   = body.get("title", "Document")
    if not content:
        raise HTTPException(status_code=400, detail="No content to export")

    # Resolve DejaVu Sans from matplotlib's bundled fonts —
    # matplotlib is already a project dependency so this path is always valid.
    mpl_fonts = os.path.join(matplotlib.get_data_path(), "fonts", "ttf")
    dejavu_r  = os.path.join(mpl_fonts, "DejaVuSans.ttf")
    dejavu_b  = os.path.join(mpl_fonts, "DejaVuSans-Bold.ttf")

    pdf = FPDF()
    pdf.add_font("DejaVu", "",  dejavu_r)
    pdf.add_font("DejaVu", "B", dejavu_b)
    pdf.set_margins(left=20, top=20, right=20)
    pdf.add_page()

    # Title — bold, centred
    pdf.set_font("DejaVu", "B", 14)
    pdf.multi_cell(pdf.epw, 10, title, align="C")
    pdf.ln(4)

    # Body — one multi_cell per line so blank lines become spacing
    pdf.set_font("DejaVu", "", 11)
    for line in content.split("\n"):
        pdf.multi_cell(pdf.epw, 7, line)

    pdf_bytes = pdf.output()
    safe_title = title.encode("ascii", "ignore").decode("ascii").replace(" ", "_").replace("/", "-").replace("\\", "-")
    return Response(
        content=pdf_bytes,
        media_type="application/pdf",
        headers={"Content-Disposition": f'attachment; filename="{safe_title}.pdf"'}
    )
